name: Bug Report ❌
description: Report an abnormal behavior.
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Is it a known issue?
      description: |
        Please check if your issue has already been reported by searching through [existing issues](https://github.com/Daminoup88/WattSeal/issues). Duplicate reports make it harder for us to track and fix bugs efficiently.
      options:
        - label: I have searched the existing issues.
          required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: What is the issue? What did you expect to happen? Please provide the steps to reproduce the bug.
      placeholder: Describe the bug clearly.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: WattSeal version
      description: You can see the version at the bottom left of the app.
      placeholder: "e.g. 1.0.0"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Select the operating system you're running the app on.
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true

  - type: dropdown
    id: admin
    attributes:
      label: Running as admin/root?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional information
      description: Do you want to add anything or paste any relevant logs? You can find them in the collector.log file next to the app executable.
      render: shell

  - type: upload
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
